mod cors_preflight;
mod file_routes;
mod metadata_routes;
mod scenes_routes;
mod audio_routes;
mod user_routes;
mod correlation_routes;
mod features_routes;
mod index_routes;
mod state_routes;
mod terms_routes;

pub use self::cors_preflight::*;
pub use self::file_routes::*;
pub use self::index_routes::*;
pub use self::metadata_routes::*;
pub use self::scenes_routes::*;
pub use self::audio_routes::*;
pub use self::user_routes::*;
pub use self::correlation_routes::*;
pub use self::features_routes::*;
pub use self::state_routes::*;
pub use self::terms_routes::*;